### ISSUE TITLE
Consider adding the slides of my BEM talk —only if awesome!

### ISSUE THREAD

**Issue by battaglr** [sturobson/BEM-resources#2]
Hi! I just gave a talk about BEM and released the slides on SpeakerDeck —as public domain. If —and only if— you find them awesome, feel free to add them to the list.
- Link: [B__E_M](https://speakerdeck.com/battaglr/bem).

Thanks and great awesome list!

**Comment by sturobson** [comment]
Hi! I've now added this, thanks for raising the issue.

**Comment by battaglr** [comment]
Great! Thank you! :)
